CREATE TABLE Personnel (
    idP INT PRIMARY KEY AUTO_INCREMENT,
    prenom VARCHAR(30) NOT NULL,
    nom VARCHAR(30) NOT NULL,
    dateEntree DATE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE Competence (
    idC VARCHAR(4) PRIMARY KEY,
    nomEn VARCHAR(50) NOT NULL,
    nomFr VARCHAR(50) NOT NULL
);

CREATE TABLE CompetencePersonnel (
    idP INT,
    idC VARCHAR(4),
    PRIMARY KEY (idP, idC),
    FOREIGN KEY (idP) REFERENCES Personnel(idP) ON DELETE CASCADE,
    FOREIGN KEY (idC) REFERENCES Competence(idC) ON DELETE CASCADE
);